### PR TITLE
Fix: One column of pixels means 4 skip bytes in 32bpp.

### PR DESCRIPTION
**Pull request by Alberth289346**
Cropping removes columns of pixels, but a column is 4 channels wide in RGBA.

Tested by sadger, confirmed to be working for 1 removed column at the left.

### CODE REVIEW

**Comment by TheCycoONE** [comment]
Do you think this deserves a comment?

**Comment by TheCycoONE** [comment]
Or a const like RGBA_BYTES_PER_PIXEL.  I would really like to reduce the number of undocumented magic numbers.

**Comment by Alberth289346** [comment]
Good idea, fixed.
In the second commit, I did some more magic reduction, but mainly made the doxygen documentation more complete and accessible.


I find it confusing that some doxymentation must be in the .h file, and others (of static members, and local constants) must be in .cpp. It's hard to see whether everything is documented.

The doxymentation style is also hard to type (//! for the first line, /*! .. */ for the other text), I don't really see the purpose of that. Simplifying it would be welcome.

**Comment by TheCycoONE** [comment]
Sorry, forgot about this

**Pull request merged**
